---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: debian-8
  - name: debian-9
  - name: centos-7
  - name: ubuntu-16.04

suites:
  - name: service
    run_list:
      - flannel_test::service
  - name: docker_integration
    run_list:
      - flannel_test::docker
